language: java
jdk: oraclejdk8

install:
  - "sudo apt-get purge openjdk*"
  - "sudo add-apt-repository -y ppa:webupd8team/java"
  - "sudo apt-get update"
  - "sudo apt-get install oracle-java8-installer"

notifications:
  irc:
    channels: chat.freenode.net#bisq
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true