[versions]
apache-commons-lang3 = { strictly = '3.11' }
apache-httpclient = { strictly = '4.5.12' }
apache-httpcore = { strictly = '4.4.13' }

bitcoinj = { strictly = 'e1cb2a17998b6071b1a10ef17f80cbf424f4255f' }
bouncycastle = { strictly = '1.63' }

commons-codec = { strictly = '1.13' }
commons-io = { strictly = '2.6' }

cowwoc-diff-match-patch = { strictly = '1.2' }

fontawesomefx = { strictly = '8.0.0' }
fontawesomefx-commons = { strictly = '9.1.2' }
fontawesomefx-materialdesign-font = { strictly = '2.0.26-9.1.2' }

fxmisc-easybind = { strictly = '1.0.3' }

google-findbugs = { strictly = '3.0.2' }
google-gson = { strictly = '2.8.6' }
google-guava = { strictly = '30.1.1-jre' }
google-guice = { strictly = '5.0.1' }

grpc = { strictly = '1.42.1' }
hamcrest = { strictly = '2.2' }

jackson = { strictly = '2.12.1' }
javax-annotation = { strictly = '1.2' }
jcsv = { strictly = '1.4.0' }
jetbrains-annotations = { strictly = '13.0' }
jfoenix = { strictly = '9.0.10' }
jopt = { strictly = '5.0.4' }
jsonrpc4j = { strictly = '1.6.0.bisq.1' }

junit-jupiter = { strictly = '5.7.0' }

kotlin = { strictly = '1.3.41' }
logback = { strictly = '1.1.11' }
lombok = { strictly = '1.18.22' }
mockito = { strictly = '4.0.0' }
natpryce-make-it-easy = { strictly = '4.0.1' }
netlayer = { strictly = '0.7.6' }
protobuf = { strictly = '3.19.1' }
qrgen = { strictly = '1.3' }
slf4j = { strictly = '1.7.30' }

[libraries]
apache-httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "apache-httpclient" }
apache-httpcore = { module = "org.apache.httpcomponents:httpcore", version.ref = "apache-httpcore" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }

bitcoinj = { module = "com.github.bisq-network:bitcoinj", version.ref = "bitcoinj" }
bouncycastle-bcpg-jdk15on = { module = "org.bouncycastle:bcpg-jdk15on", version.ref = "bouncycastle" }

commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }

cowwoc-diff-match-patch = { module = "org.bitbucket.cowwoc:diff-match-patch", version.ref = "cowwoc-diff-match-patch" }

fontawesomefx = { module = "de.jensd:fontawesomefx", version.ref = "fontawesomefx" }
fontawesomefx-commons = { module = "de.jensd:fontawesomefx-commons", version.ref = "fontawesomefx-commons" }
fontawesomefx-materialdesign-font = { module = "de.jensd:fontawesomefx-materialdesignfont", version.ref = "fontawesomefx-materialdesign-font" }

fxmisc-easybind = { module = "org.fxmisc.easybind:easybind", version.ref = "fxmisc-easybind" }

google-findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "google-findbugs" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
google-guava = { module = "com.google.guava:guava", version.ref = "google-guava" }
google-guice = { module = "com.google.inject:guice", version.ref = "google-guice" }

grpc-core = { module = "io.grpc:grpc-core", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }

hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }

jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

javax-annotation = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation" }
jcsv = { module = "com.googlecode.jcsv:jcsv", version.ref = "jcsv" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jfoenix = { module = "com.jfoenix:jfoenix", version.ref = "jfoenix" }
jopt = { module = "net.sf.jopt-simple:jopt-simple", version.ref = "jopt" }
jsonrpc4j = { module = "com.github.bisq-network:jsonrpc4j", version.ref = "jsonrpc4j" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
natpryce-make-it-easy = { module = "com.natpryce:make-it-easy", version.ref = "natpryce-make-it-easy" }

netlayer-tor-external = { module = "com.github.bisq-network.netlayer:tor.external", version.ref = "netlayer" }
netlayer-tor-native = { module = "com.github.bisq-network.netlayer:tor.native", version.ref = "netlayer" }

protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
qrgen = { module = "net.glxn:qrgen", version.ref = "qrgen" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
